version: '3.1'

services:
  postgres:
    image: postgres:13.3
    container_name: postgressdb
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    env_file: .env

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmindb
    env_file: .env
    ports:
      - 5050:80
    depends_on:
      - postgres

  back:
    image: back-tiempo
    container_name: back
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    restart: always
    networks:
      - mynetwork

  front:
    image: front-tiempo
    container_name: front
    ports:
      - 5173:80
    environment:
      - REACT_APP_API_BASE_URL=http://back:8080
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
